/** Curated product shortcuts over generated maps (stable app-facing keys). */

import { ZatGoCoreApi } from "./generated/methods";

/** Tracker domain app (`tracker.api.v1.*`). */
export const TrackerApi = {
  projectsList: "tracker.api.v1.projects.list_projects",
  projectsGet: "tracker.api.v1.projects.get_project",
  projectsCreate: "tracker.api.v1.projects.create_project",
  projectsAddMember: "tracker.api.v1.projects.add_member",
  tasksList: "tracker.api.v1.tasks.list_tasks",
  tasksGet: "tracker.api.v1.tasks.get_task",
  tasksCreate: "tracker.api.v1.tasks.create_task",
  updateTaskStatus: "tracker.api.v1.tasks.update_status",
  tasksAssign: "tracker.api.v1.tasks.assign",
  ticketsList: "tracker.api.v1.tickets.list_tickets",
  ticketsGet: "tracker.api.v1.tickets.get_ticket",
  ticketsCreate: "tracker.api.v1.tickets.create_ticket",
  ticketsAssign: "tracker.api.v1.tickets.assign",
  hierarchyMyTree: "tracker.api.v1.hierarchy.my_tree",
  hierarchyOrgTree: "tracker.api.v1.hierarchy.org_tree",
  hierarchyAssign: "tracker.api.v1.hierarchy.assign",
  hierarchySeedDemo: "tracker.api.v1.hierarchy.seed_demo",
  activityActive: "tracker.api.v1.activity.active",
  activityStart: "tracker.api.v1.activity.start",
  activityPause: "tracker.api.v1.activity.pause",
  activityNext: "tracker.api.v1.activity.next",
  activityStop: "tracker.api.v1.activity.stop",
  activityRunningNow: "tracker.api.v1.activity.running_now",
  filtersGetPresets: "tracker.api.v1.filters.get_presets",
  filtersSetLast: "tracker.api.v1.filters.set_last",
  filtersSavePreset: "tracker.api.v1.filters.save_preset",
  filtersDeletePreset: "tracker.api.v1.filters.delete_preset",
  hoursByProject: "tracker.api.v1.reports.hours_by_project",
  hoursByUser: "tracker.api.v1.reports.hours_by_user",
} as const;

export const ZatGoApi = {
  health: {
    ping: ZatGoCoreApi.health.ping,
    catalog: ZatGoCoreApi.health.catalog,
    status: ZatGoCoreApi.health.status,
  },
  devices: {
    registerToken: "zatgo_core.api.v1.devices.register_token",
    unregisterToken: "zatgo_core.api.v1.devices.unregister_token",
    sendToUser: "zatgo_core.api.v1.devices.send_to_user",
  },
  tracker: TrackerApi,
  goVan: {
    ping: ZatGoCoreApi.goVan.health.ping,
    status: ZatGoCoreApi.goVan.health.status,
    tripsList: ZatGoCoreApi.goVan.trips.list,
    tripsGet: ZatGoCoreApi.goVan.trips.get,
  },
  delivery: {
    ping: ZatGoCoreApi.delivery.health.ping,
    status: ZatGoCoreApi.delivery.health.status,
    stopsList: ZatGoCoreApi.delivery.stops.list,
    stopsGet: ZatGoCoreApi.delivery.stops.get,
    stopsCreate: ZatGoCoreApi.delivery.stops.create,
    stopsAssign: ZatGoCoreApi.delivery.stops.assign,
    stopsUpdate: "zatgo_core.api.v1.delivery.stops.update",
    stopsAccept: "zatgo_core.api.v1.delivery.stops.accept",
    stopsReject: "zatgo_core.api.v1.delivery.stops.reject",
    stopsReachRestaurant: "zatgo_core.api.v1.delivery.stops.reach_restaurant",
    stopsPickup: "zatgo_core.api.v1.delivery.stops.pickup",
    stopsStartDelivery: "zatgo_core.api.v1.delivery.stops.start_delivery",
    stopsCompleteDelivery: "zatgo_core.api.v1.delivery.stops.complete_delivery",
    stopsFailDelivery: "zatgo_core.api.v1.delivery.stops.fail_delivery",
    trackingPing: "zatgo_core.api.v1.delivery.tracking.ping",
    trackingMe: "zatgo_core.api.v1.delivery.tracking.me",
    boysList: ZatGoCoreApi.delivery.boys.list,
    boysGet: ZatGoCoreApi.delivery.boys.get,
    boysEnsure: ZatGoCoreApi.delivery.boys.ensure,
    /** Create ZG Delivery Boy — not yet in generated OpenAPI map. */
    boysCreate: "zatgo_core.api.v1.delivery.boys.create",
  },
  restoPos: {
    ping: ZatGoCoreApi.restoPos.health.ping,
    status: ZatGoCoreApi.restoPos.health.status,
    catalogList: ZatGoCoreApi.restoPos.catalog.list,
    catalogGet: ZatGoCoreApi.restoPos.catalog.get,
    kdsTicketsList: ZatGoCoreApi.restoPos.kdsTickets.list,
    kdsTicketsGet: ZatGoCoreApi.restoPos.kdsTickets.get,
    kdsTicketsAdvance: ZatGoCoreApi.restoPos.kdsTickets.advance,
    kdsTicketsRecall: ZatGoCoreApi.restoPos.kdsTickets.recall,
    kdsTicketsBumpStation: ZatGoCoreApi.restoPos.kdsTickets.bumpStation,
  },
  warehouse: {
    ping: ZatGoCoreApi.warehouse.health.ping,
    status: ZatGoCoreApi.warehouse.health.status,
    stockList: ZatGoCoreApi.warehouse.stock.list,
    stockGet: ZatGoCoreApi.warehouse.stock.get,
  },
  crm: {
    ping: ZatGoCoreApi.crm.health.ping,
    status: ZatGoCoreApi.crm.health.status,
    leadsList: ZatGoCoreApi.crm.leads.list,
    leadsGet: ZatGoCoreApi.crm.leads.get,
  },
  service: {
    ping: ZatGoCoreApi.service.health.ping,
    status: ZatGoCoreApi.service.health.status,
    ticketsList: ZatGoCoreApi.service.tickets.list,
    ticketsGet: ZatGoCoreApi.service.tickets.get,
  },
  hr: {
    ping: ZatGoCoreApi.hr.health.ping,
    status: ZatGoCoreApi.hr.health.status,
    employeesList: ZatGoCoreApi.hr.employees.list,
    employeesGet: ZatGoCoreApi.hr.employees.get,
  },
  fleet: {
    ping: ZatGoCoreApi.fleet.health.ping,
    status: ZatGoCoreApi.fleet.health.status,
    vehiclesList: ZatGoCoreApi.fleet.vehicles.list,
    vehiclesGet: ZatGoCoreApi.fleet.vehicles.get,
  },
  accounting: {
    ping: ZatGoCoreApi.accounting.health.ping,
    status: ZatGoCoreApi.accounting.health.status,
    invoicesList: ZatGoCoreApi.accounting.invoices.list,
    invoicesGet: ZatGoCoreApi.accounting.invoices.get,
  },
  customerPortal: {
    ping: ZatGoCoreApi.customerPortal.health.ping,
    status: ZatGoCoreApi.customerPortal.health.status,
    ordersList: ZatGoCoreApi.customerPortal.orders.list,
    ordersGet: ZatGoCoreApi.customerPortal.orders.get,
  },
  vendorPortal: {
    ping: ZatGoCoreApi.vendorPortal.health.ping,
    status: ZatGoCoreApi.vendorPortal.health.status,
    purchaseOrdersList: ZatGoCoreApi.vendorPortal.purchaseOrders.list,
    purchaseOrdersGet: ZatGoCoreApi.vendorPortal.purchaseOrders.get,
  },
  admin: {
    ping: ZatGoCoreApi.admin.health.ping,
    status: ZatGoCoreApi.admin.health.status,
    overviewList: ZatGoCoreApi.admin.overview.list,
    overviewGet: ZatGoCoreApi.admin.overview.get,
  },
  bi: {
    ping: ZatGoCoreApi.bi.health.ping,
    status: ZatGoCoreApi.bi.health.status,
    reportsList: ZatGoCoreApi.bi.reports.list,
    reportsGet: ZatGoCoreApi.bi.reports.get,
  },
  documentation: {
    ping: ZatGoCoreApi.documentation.health.ping,
    status: ZatGoCoreApi.documentation.health.status,
    metaList: ZatGoCoreApi.documentation.meta.list,
    metaGet: ZatGoCoreApi.documentation.meta.get,
  },
} as const;
